---
- name: Link Systemd Service
  ansible.builtin.file:
    src: "{{ project_root }}/system/keycloak-docker.service"
    dest: "/etc/systemd/system/keycloak.service"
    state: link
  become: yes

- name: Restart Keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
  become: yes
