$ANSIBLE_VAULT;1.1;AES256
39313638386662653361646365323530346334343837356563626561636163636333363439666431
6331623266353863396262626538316365316330633738610a623139373231376563346231663336
34316662336631643536363139363232636330643930343438313437326463656636373035333335
3861646337646662640a373761356638653036636661346163383830363730313264373033373030
38626562633935613663363033653634363337356334393963636232333665353732313737656335
30396563623436303234663938623133383061373639343261333232393761306239303164323535
35643734626531623437666263343130636364386433376635613264316364306363666162626665
34656136656366656333666163363131633965356362643835396637643237633733383161306562
3062
