services:
  roonserver:
    image: steefdebruijn/docker-roonserver:latest
    container_name: roonserver
    restart: unless-stopped
    # Network mode host is verplicht voor Roon discovery
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      # 1. De applicatie data (Nu lokaal in de container map!)
      - ./data:/var/roon
      
      # 2. De backup locatie
      - /mnt/backup/Roon_backup:/var/roon/RoonBackups
      
      # 3. De muziek bestanden
      - /mnt/roon:/music
